# -*- coding: utf-8 -*-
"""Trabalho_final_Desenvolvimento_de_um_software_04_09_Eduardo_Serafim.ipynb
Automatically generated by Colab.
"""

"""##        Módulos ========= Funções          """

"""##Módulo 1 - Matemática

###Operações Simples"""

def f1_matematica():
  print('                        __________Operações simples___________ ')
  print ('\n')
  print ('1 - Soma')
  print ('2 - Subtração')
  print ('3 - Multiplicação')
  print ('4 - Divisão')
  print ('\n')
  opcao = int(input('Digite qual tipo de operação deseja realizar (1, 2, 3 ou 4): '))

  if opcao == 1:

    soma = 0
    while True:
      n = float(input('Informe um número a ser incluído na soma: '))

      soma += n

      parada = input('Deseja continuar (S) ou (N):' )

      print ('\n')

      if parada.lower() == 'n':
        print (f'O resultado da soma é: {soma:.2f}')
        break

  if opcao == 2:

   n1 = float(input('Digite o primeiro número da subtração: '))
   n2 = float(input('Digite o segundo número da subtração: '))

   print ('\n')
   total = n1 - n2
   print (f'O resultado da subtração é: {total:.2f}')

  if opcao == 3:

    n1 = float(input('Digite o primeiro número da multiplicação: '))
    n2 = float(input('Digite o segundo número da multiplicação: '))

    print ('\n')
    total = n1 * n2
    print (f'O resultado da multiplicação é: {total:.2f}')

  if opcao == 4:

    n1 = float(input('Digite o primeiro número da divisão: '))
    n2 = float(input('Digite o segundo número da divisão: '))

    print ('\n')
    total = n1 / n2

    if n2 == 0:
      print ('Divisão inválida, digite um denominador diferente de zero.')

    else:
      print (f'O resultado da divisão é: {total:.2f}')

"""###Tabuada"""

def f2_matematica():

   print ('                          __________ Tabuada _________ ')
   print('\n')
   contador = 0
   nf = int(input('Digite um número para a tabuada: '))         #nf = número fixo
   n = int(input('Digite até qual número serão efetuadas as multiplicações de sua tabuada: '))

   print ('\n')

   while contador <= n:

    resultado = nf * contador
    print (f'{nf} x {contador} = {resultado}')

    contador += 1

"""###Fatorial"""

def f3_matematica():

  print ('                          __________ Fatorial _________ ')
  print ('\n')
  num = int(input('Digite um número: '))

  f = num
  fatorial = 1

  while f > 1:

    fatorial *= f
    f -= 1

  print (f'O fatorial do número digitado é {fatorial}')

"""###Fibonacci"""

def f4_matematica():
  print('                         __________ Fibonacci __________')
  print ('\n')

  a = 1
  b = 1

  contador = 1
  resultado = []

  n_termos = int(input("Digite quantos termos você deseja ver na sequência de Fibonacci: "))
  while contador <= n_termos:

    resultado.append(a)
    c = a + b
    a = b
    b = c
    contador += 1

  print (resultado)

"""##Módulo 2 - Texto

###Modificar texto
"""

def f1_texto():

  print ('              _____ Modificar Texto _____')
  print ('\n')

  texto = input('Digite o texto que deseja modificar : ')
  formatacao = int(input('Deseja colocar o texto em caixa alta (1), caixa baixa (2) ou capitalizado (3) ? '))
  print ('\n')

  if formatacao == 1:
    print (f'Texto modificado: {texto.upper()}')

  elif formatacao == 2:
    print (f'Texto modificado: {texto.lower()}')

  else:
    print (f'Texto modificado: {texto.capitalize()}')

"""###Contagem de ocorrências"""

def f2_texto():

    print ('              _____ Contagem de ocorrências _____')
    print ('\n')

    texto = input('Digite o seu texto aqui: ')
    termo = input('Digite o termo que você deseja encontrar: ')

    #lower para evitar divergências entre o texto e o termo

    mudanca_de_texto = texto.lower()
    contagem = mudanca_de_texto.count(termo.lower())

    print ('\n')

    print(f'O termo ({termo}) foi encontrado {contagem} vezes no texto.')

    parada = input('Deseja encontrar outra palavra (S) ou (N): ')

    print ('\n')

"""###Recortes de texto"""

def f3_texto():

    print("             _____ Recortes de texto _____")
    print('\n')
    texto = input("Digite um texto: ")
    termo = input("Digite o termo que você deseja encontrar: ")
    print ('\n')

    mudanca_de_texto = texto.lower()
    mudanca_termo = termo.lower()
    tamanho_termo = len(termo)
    contagem_de_ocorrencias = mudanca_de_texto.count(mudanca_termo)

    while True:


      print(f"O(s) termo(s) aparece '{contagem_de_ocorrencias}' vez(s). ")

      while contagem_de_ocorrencias > 0:

        contagem_de_ocorrencias -= 1
        comeco = mudanca_de_texto.find(mudanca_termo)


        # Calcular os índices de recorte
        comeco_recorte = max(0, comeco - 3) #
        fim_recorte = min(len(texto), comeco + tamanho_termo + 3)

        # mostra os 3 antes e os 3 depois da palavra que o usuario escolheu
        recorte = texto[comeco_recorte:fim_recorte]
        mudanca_de_texto = mudanca_de_texto[:comeco_recorte] + mudanca_de_texto[fim_recorte:]

        print(f"Recorte do(s) termo(s) buscado(s): '{recorte}'")
        print ('\n')

      parada = input("Deseja parar (S) ou (N)? ")

      if parada.lower() == 's':
          break

"""###Gerador de Senhas"""

import random
def f4_texto():

    print("             _____ Gerador de Senhas _____")
    print('\n')

    letras_maiusculas = ["A", "B", "C","D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "X", "W", "Y", "Z"]
    letras_minusculas = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "x", "w", "y", "z"]
    numeros = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
    caracteres = ["!", "@", "?", "#", "$", "%", "*"]
    soma_caracteres = letras_maiusculas + letras_minusculas + numeros + caracteres

    tamanho_da_senha = int(input("Digite a quantidade de caracteres para sua senha: "))

    senha = []
    for _ in range(tamanho_da_senha):
      senha.append(random.choice(soma_caracteres))

    if tamanho_da_senha == 0:

      print ('\n')
      print("Não foi possível gerar a senha!")

    else:

     print ('\n')
     print("Sua senha é: " , ''.join(map(str,senha)))

"""##Módulo 3 - Escola

###Cálculo de média aritmética de **notas**
"""

def f1_escola():
  print ('               _____ Cálculo de Média Aritmética de Notas _____ ')
  print('\n')

  contador= 1
  total = 0


  while True:

    n = float(input(f'Digite a {contador}º nota: '))
    total += n

    parada = input('Deseja adicionar mais notas (S) ou (N) ? ')
    print ('\n')

    if parada.lower() == 'n':
      break

    contador = contador + 1

  media = total / contador
  print (f'A média aritmética das notas fornecidas é: {media:.2f}')

"""###Média ponderada de notas"""

def f2_escola():
  print ('               _____ Cálculo de Média Ponderada de Notas _____ ')
  print('\n')

  contador= 1
  totaln = 0
  totalp = 0

  while True:

    n = float(input(f'Digite a {contador}º nota: '))
    p = float(input(f'Digite o peso dessa nota: '))

    totaln += (n * p)         #totaln = total das notas multiplicadas por seus respectivos pesos
    totalp += p               #totalp = total da soma de pesos

    parada = input('Deseja adicionar mais notas (S) ou (N) ? ')
    print ('\n')

    if parada.lower() == 'n':
      break

    contador = contador + 1

  media = totaln / totalp
  print (f'A média ponderada das notas fornecidas é: {media:.2f}')

"""###Cálculo de porcentagem de faltas

"""

def f3_escola():

  print ('              _____Cálculo de porcentagem de faltas_____')
  print ('\n')

  ch = int(input('Qual a carga horária da discplina?  '))
  ha = int(input('Qual a quantidade de horas por aula?  '))
  faltas = int(input('Digite sua quantidade de faltas: '))

  #ch = carga horária
  #ha = horas por aula

  limite_de_faltas = (ch * 0.25) / ha
  faltas_em_horas = ha * faltas

  print ('\n')

  #Percentual de faltas total:
  pft = (faltas_em_horas * 100) / ch

  print (f'Seu percentual de faltas total em relação à disciplina é de {pft:.0f}%.')

  if faltas > limite_de_faltas:

   print (f'Infelizmente você está reprovado nesta disciplina, pois você ultrapassou o limite de faltas (Máximo {limite_de_faltas:.0f}).')

  elif faltas == limite_de_faltas:

   print (f'Você está aprovado na disciplina até o momento, não podendo faltar mais nenhuma aula.')

  else:

    print (f'Você está aprovado na disciplina até o momento, podendo faltar {(limite_de_faltas - faltas):.0f} aulas, sem que haja reprovação.')

"""##Módulo 4 - Miscelâneas

###Codificar mensagem
"""

def f1_miscelaneas():

  print ('              _____ Codificar Mensagem _____')
  print ('\n')
  texto = input ("Digite um texto para ser codificado: ")
  numero = int(input('Digite um número para multiplicar: '))


  texto_codificado = []

  for caractere in texto:

      valor_ascii = ord(caractere)
      codigo_codificado = valor_ascii * numero
      texto_codificado.append(str(codigo_codificado))

  resultado = ' '.join(texto_codificado)

  print(f'Texto codificado: {resultado}')

"""###Decodificar Mensagem"""

def f2_miscelaneas():

    print ('              _____ Decodificar Mensagem _____')
    print ('\n')
    texto_codificado = input("Digite o texto codificado: ")
    numero = int(input('Digite o número usado para multiplicar: '))

    codigos = texto_codificado.split()

    texto_decodificado = []

    for codigo in codigos:

        valor_codificado = int(codigo)
        valor_ascii = valor_codificado // numero
        caractere = chr(valor_ascii)
        texto_decodificado.append(caractere)

    resultado = ''.join(texto_decodificado)

    print(f'Texto decodificado: {resultado}')

"""###Gerar árvore de Natal"""

def f3_miscelaneas():

  print ('              _____ Gerar Árvore de Natal 🎄 _____')
  print ('\n')
  niveis = int(input('Quantos níveis deseja que sua árvore possua ? '))
  print ('\n')

  contador = 1
  aster = '*'
  espaco = (niveis + 1) * ' '
  t = niveis

  print (f'{espaco}{aster}')

  espaco = (niveis) * ' '

  while contador <= niveis:

      t -= 1
      print (f'{espaco}/{aster}\\')
      aster = aster + '**'
      contador += 1
      espaco = t * ' '

  espaco = (niveis) * ' '
  print (f'{espaco}|||')

"""###Menu Principal"""

print ('___________ Bem vindo ao Software de Ferramentas Cotidianas 💡🎉______________')
print ('\n')

print ('Este software possui diversas ferramentas, ditribuídas (de acordo com a relação entre elas) em 4 módulos:')
print ('\n')

print ('1 - Matemática')
print ('2 - Texto')
print ('3 - Escola')
print ('4 - Miscelâneas')
print ('\n')

opcao_geral = int(input('Digite o número do módulo que deseja acessar (1, 2, 3 ou 4): '))
print ('\n')

if opcao_geral == 1:

  print ('               __________ Módulo 1 - Matemática __________    ')
  print ('Este módulo possui funcionalidades relacionadas a operações matemáticas diversas:')
  print ('\n')
  print ('1 - Operações simples')
  print ('2 - Tabuada')
  print ('3 - Fatorial')
  print ('4 - Fibonacci')
  print ('\n')

  opcao_modulo1 = int(input('Escolha uma das funcionalidades (1, 2, 3, ou 4): '))
  print ('\n')

  if opcao_modulo1 == 1:    # f1_matemática: significa ferramenta 1
        f1_matematica()     # do módulo matemática, as outras seguem a mesma lógica.

  elif opcao_modulo1 == 2:
        f2_matematica()

  elif opcao_modulo1 == 3:
        f3_matematica()

  elif opcao_modulo1 == 4:
        f4_matematica()

elif opcao_geral == 2:

  print ('              __________ Módulo 2 - Texto __________   ')
  print ('Este módulo possui funcionalidades relacionadas à manipulação de textos:')
  print ('\n')
  print ('1 - Modificar texto')
  print ('2 - Contagem de ocorrências')
  print ('3 - Recortes de texto')
  print ('4 - Gerador de senhas')
  print ('\n')
  opcao_modulo2 = int(input('Escolha uma das funcionalidades (1, 2, 3, ou 4): '))
  print ('\n')

  if opcao_modulo2 == 1:
        f1_texto()
                                    # f1_texto: significa ferramenta 1 do módulo texto,
  elif opcao_modulo2 == 2:          #           as outras seguem a mesma lógica.
        f2_texto()

  elif opcao_modulo2 == 3:
       f3_texto()

  elif opcao_modulo2 == 4:
       f4_texto()



elif opcao_geral == 3:

  print ('               __________ Módulo 3 - Escola __________   ')
  print ('Este módulo possui operações diversas relacionadas à vida escolar de um estudante:')
  print ('\n')
  print ('1 - Cálculo de média aritmética de notas')
  print ('2 - Média ponderada de notas')
  print ('3 - Cálculo de porcentagem de faltas')
  print ('\n')
  opcao_modulo3 = int(input('Escolha uma das funcionalidades (1, 2, 3 ou 4): '))
  print ('\n')

  if opcao_modulo3 == 1:
        f1_escola()
                         # f1_escola: significa ferramenta 1 do módulo escola,
  elif opcao_modulo3 == 2:              # as outras seguem a mesma lógica.
        f2_escola()

  elif opcao_modulo3 == 3:
       f3_escola()


elif opcao_geral == 4:

  print ('             __________ Módulo 4 - Miscelâneas __________    ')
  print ('Este módulo possui operações diversas não categorizadas:')
  print ('\n')
  print ('1 - Codificar mensagem')
  print ('2 - Decodificar mensagem')
  print ('3 - Gerar árvore de Natal')
  print ('\n')
  opcao_modulo4 = int(input('Escolha uma das funcionalidades (1, 2, 3 ou 4): '))
  print ('\n')

  if opcao_modulo4 == 1:
       f1_miscelaneas()
                             # f1_miscelâneas: significa ferramenta 1 do módulo miscelâneas,
  elif opcao_modulo4 == 2:                    #           as outras seguem a mesma lógica.
       f2_miscelaneas()

  elif opcao_modulo4 == 3:
       f3_miscelaneas()

